name: cd

on:
  workflow_dispatch:
  push:
    tags: 
      - "*.*.*"

permissions:
  id-token: write

jobs:
  npm: 
    runs-on: ubuntu-latest   
    strategy:
      fail-fast: false
      matrix:
        package: ['gly-cli', 'gly-engine', 'gly-engine-lite', 'core-native-html5']
    steps:
      -
        uses: actions/checkout@master
      - 
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.4"
      -
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      -
        run: |
          lua tools/cd_npm_${{ matrix.package }}.lua
      - 
        working-directory: ./dist
        run: |
          npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
