name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    if: github.event_name == 'push' || github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        lua_version: ['5.1', '5.3', '5.4']
    steps:
    -
      uses: actions/checkout@master
    - 
      uses: leafo/gh-actions-lua@v10
      with:
        luaVersion: ${{ matrix.lua_version }}
    -
      uses: leafo/gh-actions-luarocks@v4
    -
      run: |
        luarocks install luacov
        luarocks install luaunit
    -
      run: |
        ./cli.sh cli-test --coverage
    - 
      if: (matrix.lua_version == '5.4') && (github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository)
      run: |
        bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}

  version:
    if: github.event_name == 'push'
    name: test version
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@master
    - 
      uses: leafo/gh-actions-lua@v10
      with:
        luaVersion: '5.4'
    -
      run: |
        lua tools/ci_version_local.lua

  lint:
    if: github.event_name == 'push' || github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        core: ['native']
    steps:
    -
      uses: actions/checkout@master
    - 
      uses: leafo/gh-actions-lua@v10
      with:
        luaVersion: '5.4'
    -
      run: |
        wget https://github.com/luau-lang/luau/releases/download/0.644/luau-ubuntu.zip
        unzip luau-ubuntu.zip
    -
      run: |
        lua tools/ci_luau-analyze.lua ${{ matrix.core }}
    -
      run: |
        ./luau-analyze dist/main.lua
